### ISSUE TITLE
The correctness of EvalExponentialPdf method in thinkbayes2.py

### ISSUE THREAD

**Issue by 18fanfan** [AllenDowney/ThinkBayes2#16]
Dear professor Downey,

In chapter 7.6, you would like to compute the time between goals and the code in EvalExponentialPdf method is:

<pre>
return lam*math.exp(-lam*x)
</pre>

but I think the probability between two events is:

<pre>
return math.exp(-lam*x)
</pre>
The first term lam variable should be dropped.

Here comes my justification:
Assume T is the time interval between two goals. The Pr(T > x ) means the probability in a certain time interval x should not occur scoring. so we take the k=0 to the Poisson distribution, then we got math.exp(-lam*x).

Although I know the EvalExponentialPdf only be called by MakeExponentialPmf, and the lam variable will be canceled out after Normalize function. so the result stays the same.
But I still want to confirm with you the correctness of the method. 
Thanks in advance!

**Comment by AllenDowney** [comment]
I believe the function EvalExponentialPdf correctly computes the PDF of the exponential distribution. Please check
https://en.wikipedia.org/wiki/Exponential_distribution and let me know if you disagree.

**Comment by 18fanfan** [comment]
Dear professor Downey,

I check the wiki, and it is the right definition. 
I also read this article https://neurophysics.ucsd.edu/courses/physics_171/exponential.pdf to realize the relation between the Poisson and exponential distribution.

I think I misunderstood the meaning of Pr(T > x) to explain the distribution of two goals.
