### ISSUE TITLE
Two 'utils.py' files in /code directory

### ISSUE THREAD

**Issue by Ver1s** [AllenDowney/ThinkBayes2#23]
Hello
I am going through the notebook for Chapter 1, and there seems to be an issue with importing _write_table_:
_from utils import write_table
write_table(table, 'table01-01')_
produces an _ImportError_.  From what I can tell, it's because _/code_ has two files named _utils.py_: one in _/code_, the other in _/code/soln/_. The function _write_table_ is defined in the latter, and import never checks there because it looks in the _utils.py_ that is in /code, the same directory as all the notebooks. Could you please take a look?

**Comment by AllenDowney** [comment]
Thanks for letting me know about this.  It sounds like you were using the repository while it was in a state of flux.  I think this is working now.
