### ISSUE TITLE
There is no test_env.py script

### ISSUE THREAD

**Issue by flothesof** [AllenDowney/ThinkBayes2#24]
Hi,
I'm currently working from your latest source and the installation instructions for a local install mention this:
```
\item To test your environment and make sure it has everything we need, run the following command:

\begin{verbatim}
python test_env.py
\end{verbatim}
```
Is this still planned? I'm not a beginner but I think this might be important for beginners to give them confidence in their correctly installing the Python stack. That's why I'm reporting on it here.

Thank you for this work of your's Allen!

Regards,
Florian

**Comment by AllenDowney** [comment]
Closing this one as it is now out of date.
