### ISSUE TITLE
exercice 1.2 in Chapter 1 formulation

### ISSUE THREAD

**Issue by flothesof** [AllenDowney/ThinkBayes2#26]
Hi Allen,

I'm trying to solve exercice 1.2 in Chapter 1. 
I have trouble understanding what you mean by "You ask if either child is a girl and they say yes." (I'm not a native speaker, so this could be the reason I have a hard time understanding that sentence).
I have come up with a way of disambiguating this sentence for me as: 
"They have Child 1 and Child 2. You ask if Child 1 is a girl and they say yes." or "They have Child 1 and Child 2. You ask if Child 2 is a girl and they say yes."  
Is this the correct interpretation?

Thanks for your help.
Regards,
Florian

**Comment by AllenDowney** [comment]
Sorry I am so slow to respond to this! The intent here is to ask something like "Is at least one of your children a girl?"
