### ISSUE TITLE
discussion on ex 9.1

### ISSUE THREAD

**Issue by francescolosterzo** [AllenDowney/ThinkBayes2#27]
Hello!

DISCLAIMER: this is not an "issue", rather a discussion about ex 9.1 (as there is no "correct" solution)
[of course feel free to close the issue if it's inappropriate, I didn't find any other place where to discuss this]

[Here](https://github.com/francescolosterzo/ThinkBayes2/blob/master/notes/Paintball.ipynb) is my worked out example and solution.

I think that the interesting point in the example in the book is that the assumption that "the opponent is like a rotating turret, equally likely to shoot in any direction", i.e. `theta` has a uniform distribution, implies that `x` is not uniform by construction (`x` ~ tan(`theta`)). I guess the key point is that P(`theta`) = uniform implies P(`x`) ~ 1/StrafingSpeed.

In my solution, to go beyond that assumption, I simply introduced a non uniform distribution of `theta`, which I made dependent on `alpha` and `beta` (long story short: if the shooter is close to a wall, he/she is more likely to shoot away from the wall). In order to implement this in the solution, I made: P(`x`) ~ P(`theta`)/StrafingSpeed.

What did other people do? What is the form P(`x`) in your more realistic case?

**Comment by AllenDowney** [comment]
No problem with using issues for discussion, but I'm going to close this just to help me keep track of what's open.
