### ISSUE TITLE
Typo in Theorem 1 from Laws of probability

### ISSUE THREAD

**Issue by GermanCM** [AllenDowney/ThinkBayes2#37]
Thanks for your amazing books dear Allen.
I found this typo by reading the early version at O'Reilly site (multiplying instead of dividing over P(B)):
![IMG_20210410_155600](https://user-images.githubusercontent.com/32896503/114272555-f082e400-9a16-11eb-9d0c-8059e61fd993.jpg)

**Comment by GermanCM** [comment]
Sorry for this, it was an issue due to the used explorer...

**Comment by AllenDowney** [comment]
No problem!
