### ISSUE TITLE
Empiricaldist module

### ISSUE THREAD

**Issue by FedeVass** [AllenDowney/ThinkBayes2#38]
Seems like there is a module missing; "empiricaldist".
Where can I find it?
Thanks

**Comment by AllenDowney** [comment]
It's on PyPI, 

https://pypi.org/project/empiricaldist/

you can install it like this:

```
pip install empiricaldist
```

This notebook walks through the API:

https://nbviewer.jupyter.org/github/AllenDowney/empiricaldist/blob/master/empiricaldist/dist_demo.ipynb

I tried to document this requirement, so maybe you can help me improve the instructions: how did you get stuck?

**Comment by FedeVass** [comment]
Hi there,
I got some error messages trying to install it with pip (I don't have them now, but they were related to the SSL certificate or similar).
So, instead, I downloaded the package and copied the py files to the library folder of my anaconda installation. Seems to be working now.
Thank you
Federico

**Comment by FedeVass** [comment]
Oh , I found the error message I was getting with pip. Here it is, in case you have a clue about what was wrong:
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)'))': /packages/64/ce/732891161f5ca77d8a50616ad3081ec307bddcaa5ad604702bdb2f7654ad/empiricaldist-0.6.1.tar.gz

**Comment by AllenDowney** [comment]
That looks like a problem with your Python installation.

It's good that you worked around it, but I suspect you will have problems with other packages you install with pip.

If you are not using Anaconda, I recommend it.

**Comment by FedeVass** [comment]
Hi again,
Yes I do have Anaconda. It's just that i have at least 2 or 3 python installations, and I believe the pip command was using the wrong one. So the manual setup worked fine.
Thanks a lot
Cheers
Federico

**Comment by AllenDowney** [comment]
Makes sense.  Glad you got it working!
