### ISSUE TITLE
Small typo in solutions to exercise 3 in ch2

### ISSUE THREAD

**Issue by nablabits** [AllenDowney/ThinkBayes2#39]
Hi Allen, 

Thanks for this fantastic resource, it's helping me a lot!

I noticed a small typo in the solutions to the 3rd exercise in [chapter 2](https://github.com/AllenDowney/ThinkBayes2/blob/master/soln/chap02.ipynb)
> If the car is behind Door 1, Monty would have opened Door 2
> If the car is behind Door 2, Monty would always Door 3
> If the car is behind Door 3, Monty would have opened Door 3

 If the car is behind Door 1, Monty would have opened Door 2
 If the car is behind Door 2, Monty would always *open* Door 3
 If the car is behind Door 3, Monty would have opened *Door 2*

If you agree with the suggestion I will be happy to open a PR fixing it.

Have a nice day

**Comment by AllenDowney** [comment]
I will get that fixed.  Thank you!

**Comment by nablabits** [comment]
Cool, feel free to close the issue when you want so.
