### ISSUE TITLE
Misleading solution for chap06 exercise "honest members"

### ISSUE THREAD

**Issue by johanwiden** [AllenDowney/ThinkBayes2#41]
I believe it is a lucky coincidence that table[312] or so gives a good likelihood. I believe that one should search table[] for the index that gives the posterior that has a max_prob() closest to 312.
I think this becomes clear if one plots the distributions for a few indices, say [0, 180, 360, 530].
Also if one considers that he values 50% and 90% are somewhat arbitrary.

**Comment by AllenDowney** [comment]
Sorry I did not get to this sooner -- it looks like this might refer to an earlier version of the solution. Please let me know if this is still an issue.
