### ISSUE TITLE
Chapter 2 Bayes' Theorem

### ISSUE THREAD

**Issue by ckchmod** [AllenDowney/ThinkBayes2#42]
I believe the function update() should return the table, not "prob_data".

def update(table):
    """Compute the posterior probabilities."""
    table['unnorm'] = table['prior'] * table['likelihood']
    prob_data = table['unnorm'].sum()
    table['posterior'] = table['unnorm'] / prob_data
    return prob_data

**Comment by AllenDowney** [comment]
That interface is as intended: the function modifies the table, so it's not necessary to return it.

And for some purposes it is useful to see the total probability of the data.
