### ISSUE TITLE
Links in the book should be collected together online

### ISSUE THREAD

**Issue by hahla** [AllenDowney/ThinkBayes2#45]
The book uses shortened URLs, which in aggregate waste the time of readers. I did not see online or in the book a link to a bibliography, so I would suggest using this repo wiki for the purpose and request others to help contribute.

This will also help identify if there are references in the book out of date, or not explicit as intended.

**Comment by AllenDowney** [comment]
One reason for the shortened URLs is that they can be updated in my .htaccess files, without changing the book.

What do you mean when you say they waste the time of readers?
