### ISSUE TITLE
Chapter 8 missing cells in zip file

### ISSUE THREAD

**Issue by discdiver** [AllenDowney/ThinkBayes2#46]
Thank you for this great resource!

The Colab notebook for chapter 8 has cells to create the france and croatia goal data. The downloaded notebook zip files do not.

**Comment by AllenDowney** [comment]
Thanks for letting me know. I will fix this when I can, but let me make sure I understand so I know how urgent it is: do you mean that there is code missing that you need, or just that the empty cells are not there, so you have to make them yourself?

**Comment by discdiver** [comment]
The code is missing. 

The markdown file says: 

"In the example, France scored 4 goals, so I'll make a copy of the prior and update it with the data."

The next cell is missing. In the Colab notebook it has:

```
france = prior.copy()
update_poisson(france, 4)
```

Same goes for Croatia.

**Comment by AllenDowney** [comment]
Sorry for my very slow reply. This should be fixed now, but please reopen this issue if not. Thanks!
