### ISSUE TITLE
'Compile' book from code

### ISSUE THREAD

**Issue by jose-ramirez** [AllenDowney/ThinkBayes2#48]
This is not exactly an issue per se, just a question of mine.

Is it possible to create this book's pdf version from source? I'm just asking because I was trying (by running `make all` inside the `book` folder), but got too many errors, so I was wondering if there's some extra steps needed, or if I'm not supposed to be able to compile the book :sweat_smile:

**Comment by AllenDowney** [comment]
I don't currently have a tool chain that produces a PDF version of this book.
