### ISSUE TITLE
Chapter 10 Solutions - Definition / Implementation mismatch for the logistic

### ISSUE THREAD

**Issue by EricRobertCampbell** [AllenDowney/ThinkBayes2#49]
In the final exercise for Chapter 10, there is a slight mismatch between the definition of the 3-parameter logistic function and its implementation. In the definition, we see that the parameter `a` is multiplying the other term in the exponent of the exponential.

![original](https://user-images.githubusercontent.com/30555202/136129572-9c1637c3-7429-4698-929e-5f4b8f2801bb.png)

However, in the implementation in the next cell, we see that the variable `a` is dividing the rest of the terms (in the assignment to `x`).

![original code](https://user-images.githubusercontent.com/30555202/136129634-4ebac925-6aef-4885-bcb8-ebaaea41e9fd.png)

The Wikipedia link also uses the convention of having the parameter `a` multiply the terms. I believe that the easiest solution would be to change the value of `a` to 1/100 and change it to multiplication in the definition of `x`.

**Comment by AllenDowney** [comment]
Got it. Will fix. Thanks!
