### ISSUE TITLE
Chapter 1 download data code isn't working

### ISSUE THREAD

**Issue by HelloWorld183L** [AllenDowney/ThinkBayes2#57]
I found that the original code seems to be outdated since it seems to use a different repository name (BiteSizeBayes) and it uses a csv file whereas the current data is in a gss_bayes folder which I don't know how to read/use (normally I use csv files). Can anyone give guidance on how to read in this data (e.g. docs) or a pointer on where to find the original GSS data? Thanks in advance.

Here's the original code for context:

`# Load the data file

from os.path import basename, exists

def download(url):
    filename = basename(url)
    if not exists(filename):
        from urllib.request import urlretrieve
        local, _ = urlretrieve(url, filename)
        print('Downloaded ' + local)
    
download('https://github.com/AllenDowney/BiteSizeBayes/raw/master/gss_bayes.csv')`

**Comment by AllenDowney** [comment]
Which file is this in?

**Comment by HelloWorld183L** [comment]
> Which file is this in?

This is in chap01.ipynb (https://github.com/AllenDowney/ThinkBayes2/blob/master/notebooks/chap01.ipynb)

**Comment by AllenDowney** [comment]
This notebook runs on Colab without problems:

https://colab.research.google.com/github/AllenDowney/ThinkBayes2/blob/master/notebooks/chap01.ipynb

I recommend running the notebooks on Colab.

I think I don't understand what you are asking.

**Comment by HelloWorld183L** [comment]
What I was trying to say was that the notebook I linked doesn't work as it cannot retrieve the data (whereas the Collab notebook works) since it ends up with a 404. I don't see a CSV file in the GitHub repository and the Collab notebook ends up using data from a **different** repository. I'll stick to the Collab notebooks for now since they seem to work just fine.

For extra context, here was the error I was getting: 

`URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1125)>`
