### ISSUE TITLE
TypeError: Series.__init__() got an unexpected keyword argument 'normalize'

### ISSUE THREAD

**Issue by Strigfox85** [AllenDowney/ThinkBayes2#58]
Hi, Professor. I am facing this  problem when I am practicing probability mass function in gss.hdf5. I am following exactly what have you teach in the slides. May I know why is this happening?  Thank you.

```
import pandas as pd
import matplotlib.pyplot as plt
from empiricaldist import Pmf
```

```
gss = pd.read_hdf('gss.hdf5','gss')
educ =gss['educ']
pmf_educ = Pmf(educ normalize=False)
```

Traceback (most recent call last):
  File "c:\Users\User\Desktop\Study\Data_Camp\courses\Exploratory Data Analysis in Python\Probability_mass_functions.py", line 30, in <module>
    pmf_educ = Pmf(educ, normalize=False)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\empiricaldist\empiricaldist.py", line 45, in __init__
    super().__init__(*args, **kwargs)
TypeError: Series.__init__() got an unexpected keyword argument 'normalize'``

**Comment by AllenDowney** [comment]
The version of `Pmf` in `empiricaldist` is a little different from the version in the DataCamp course. To make a `Pmf` from a sequence, you need

```
Pmf.from_seq([1,2,3], normalize=False)
```

This notebook is the best intro to the API.

https://nbviewer.org/github/AllenDowney/empiricaldist/blob/master/empiricaldist/dist_demo.ipynb

**Comment by Strigfox85** [comment]
I see, thank you. Professor.
