### ISSUE TITLE
Linda problem should use conditional probability when it comes to sex.

### ISSUE THREAD

**Issue by Szustarol** [AllenDowney/ThinkBayes2#63]
One thing I feel the book misses multiple times in chapter I is the fact, that Linda's sex is given in the problem description (I picked an exercise as a sample): 

> Linda is 31 years old, single, outspoken, and very bright. She majored in philosophy. As a student, she was deeply concerned with issues of discrimination and social justice, and also participated in anti-nuclear demonstrations. Which is more probable?

    Linda is a banker.

    Linda is a banker and considers herself a liberal Democrat

According to [sample solution to this exercise](http://allendowney.github.io/ThinkBayes2/chap01.html#codecell73), we should answer "Linda is a banker" with P(female & banker). However, given it is clear from the description (from the usage of "she"), that Linda is a female, this fact should be considered given, and the solution should be P(banker | female).

Of course, this fact doesn't change the answer (being a female banker is still more probable than being a liberal, democrat, female banker), however I feel like at least the answer to the above exercise needs to be changed, or the fact that multiple (In my humble opinion - valid) approaches are possible here.

**Comment by AllenDowney** [comment]
I see your point. But the way the exercises are organized, this question is meant to be about conjunction, and the next one is about conditional probability. I think the instructions are clear enough, and the answer is not exactly wrong. So I think I'll leave it as is for now. Thanks for this suggestion.

**Comment by AlisterFrench-OW** [comment]
This is my second time working through the materials, (excellent by the way) and came and looked at the issues for exactly this reason. P(female | Linda) = 1 as long as we are able to assume that "she" => female so this can be distracting to those of us who are more pedantic.

Perhaps you could swap the name for this section to a name used commonly by both men and women (such as Tyler or Francis) and give the information in a different way, or swap the gender for another attribute. 

I can't be alone in getting distracted by this confusion, and I doubt I am only the second person after Szustarol to be so distracted.

Thank you anyway for this wonderful resource.
