### ISSUE TITLE
Chapter 2 - nomenclature adjustment

### ISSUE THREAD

**Issue by vitorvilela** [AllenDowney/ThinkBayes2#72]
It's not a code issue...

Since we are applying the Diachronic Bayes, I think it is more readable to keep the H letter instead of B, in page 21 - Bayes Tables:

I call the result `unnorm` because these values are the "unnormalized posteriors".  Each of them is the product of a prior and a likelihood:

$$P(H_i)~P(D|H_i)$$

which is the numerator of Bayes's Theorem. 
If we add them up, we have

$$P(H_1)~P(D|H_1) + P(H_2)~P(D|H_2)$$

which is the denominator of Bayes's Theorem, $P(D)$.

**Comment by AllenDowney** [comment]
Yes, that's better. Thanks for the suggestion and for the kind words!
