### ISSUE TITLE
Chapter 4 - Proper Prior Probability Initialisation

### ISSUE THREAD

**Issue by iamyifan** [AllenDowney/ThinkBayes2#73]
Hi developer,

The original prior probability `prior = Pmf(1, hypos)` in Ch.4 is initialised with 1:
<img width="931" alt="image" src="https://github.com/AllenDowney/ThinkBayes2/assets/33194917/4e01f0b5-7d5e-443b-a9ed-5ca91834067e">

It's better to be initialised with `prior2 = Pmf(Fraction(1, len(hypos)), hypos)`, which is a uniform distribution, and its sum adds up to 1.

The results and the final plot are the same under `np.allclose(posterior, posterior2)`:
<img width="819" alt="image" src="https://github.com/AllenDowney/ThinkBayes2/assets/33194917/80c6d5b9-8665-45d8-a372-98e8366c6254">
<img width="437" alt="image" src="https://github.com/AllenDowney/ThinkBayes2/assets/33194917/ae6970df-3260-4838-8656-30dde4570fad">

Also, for a better understanding, the loop inside the function should be given a more detailed explanation:
<img width="539" alt="image" src="https://github.com/AllenDowney/ThinkBayes2/assets/33194917/56eb50dc-559a-4447-a490-d9a8e117d77b">

For example: 
The reason we can use a loop to multiply likelihood is that each coin-flipping experiment is independent of others, hence the $P(\theta)$ represents the probability of a coin landing in its head in the Bayesian theorem, $P(D_x|\theta)$ represents $x$-th coin-flipping experiment, where $D_x$ can be `'H'` or `'T'`. The loop represents the process of $P(D_1|\theta) \times P(D_2|\theta) \times ... \times P(D_n|\theta) = P(D|\theta)$ since they are independent of each other.

Cheers,
Yifan

**Comment by AllenDowney** [comment]
Thanks for these suggestions and sorry for taking so long to get to this! I use improper priors in a few places in the book because they get normalize after the first update anyway, so it doesn't affect the results -- as you showed.
